apiVersion: v1
kind: Namespace
metadata:
  name: bccl
kind: Service
apiVersion: v1
metadata:
  labels:
    app: yzw-bccl-cc-app
  name: bccl-service
  namespace: bccl
spec:
  ports:
    - port: 18085
      targetPort: 18085
  selector:
    app: yzw-bccl-cc-app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yzw-bccl-cc-deployment
  namespace: bccl
  labels:
    app: yzw-bccl-cc-app
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: yzw-bccl-cc-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: yzw-bccl-cc-app
    spec:
      containers:
      - name: yzw-bccl-cc-app
        image: mycce-poc1.yzw/bccl/bccl-cc:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 2
            memory: 4Gi