apiVersion: apps/v1
kind: Deployment
metadata:
  name: yzw-bccl-cc-deployment
  namespace: bccl
  labels:
    app: yzw-bccl-cc-app
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: yzw-bccl-cc-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: yzw-bccl-cc-app
    spec:
      containers:
      - name: yzw-bccl-cc-app
        image: mycce-poc1.yzw/bccl/bccl-cc:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2C
            memory: 4Gi
          limits:
            cpu: 2C
            memory: 4Gi